language: objective-c
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - node_modules/
env:
    - BUILD_TYPE=android
# Be a good travis citizen while we don't actually run the build on iOS yet.
#    - BUILD_TYPE=ios
before_install:
    - brew update
    - git clone https://github.com/creationix/nvm.git /tmp/.nvm
    - source /tmp/.nvm/nvm.sh
    - nvm install 5.0
    - nvm use --delete-prefix 5.0
    - node --version && npm --version
install:
    - . build-scripts/bootstrap.sh
script:
    - ./build-scripts/build.sh
    - . build-scripts/tag-nightly.sh
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: $ARTIFACT
    skip_cleanup: true
    overwrite: true
    on:
        tags: true
        condition: $NIGHTLY = "true"
